name: Python CI

on:
  push:
    branches:
      - section04  # Ветка, для которой будет запускаться CI
  pull_request:
    branches:
      - section04  # Ветка, для которой будет запускаться CI на pull request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Используем последние стабильные версии Python

    steps:
      # Шаг клонирования репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Очистка кэша Python, если есть конфликты с версией
      - name: Clear Python cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python

      # Установка Python версии, указанной в матрице
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Проверка доступных версий Python (диагностика, если нужно)
      - name: List available Python versions
        run: |
          sudo find /opt/hostedtoolcache/Python

      # Установка зависимостей из requirements.txt (если есть зависимости)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Запуск всех тестов
      - name: Run tests
        run: |
          python -m unittest discover
